mimir:
  structuredConfig:
    common:
      storage:
        backend: s3
        s3:
          endpoint: s3.ap-northeast-2.amazonaws.com
    blocks_storage:
      backend: s3
      s3:
        bucket_name: BUCKET_NAME
      bucket_store:
        sync_dir: /data/tsdb-sync
        index_cache:
          backend: "inmemory"

distributor:
  extraArgs:
    auth.multitenancy-enabled: false
query_frontend:
  extraArgs:
    auth.multitenancy-enabled: false

alertmanager:
  enabled: false
minio:
  enabled: false
nginx:
  enabled: false
overrides_exporter:
  enabled: false
query_scheduler:
  enabled: false
ruler:
  enabled: false