apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-prod
  namespace: jaeger
spec: 
  strategy: production
  storage:
    type: elasticsearch 
    options:
      es:
        server-urls: https://opensearch-cluster-master.opensearch.svc:9200 
        index-prefix: jaeger
        tls.skip-host-verify: true
    secretName: jaeger-secret
