alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - localhost:9093
rule_files:
  - "./rules/*.yml"

scrape_configs:
- job_name: "node_exporter"
  ec2_sd_configs:
  - region: 'ap-northeast-2'
    port: 9100
    filters:
      - name: tag:Monitoring
        values:
          - true